name: CI

on: [push]

defaults:
  run:
    shell: bash
jobs:
  macos:
    name: MacOS
    runs-on: macos-latest
    steps:
      - name: Install
        run: |
          printenv
          export PATH=/usr/bin:/bin:/usr/sbin:/sbin
          cp /usr/local/opt/gcc/lib/gcc/9/libgfortran.5.dylib .
          ls
          clang --version
          gfortran -v

# jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         build_type: [Debug, Release]
#         cxx11: [YES, NO]
#         library_type: [SHARED, STATIC]
#         compiler: [GCC, CLANG]
#
#     steps:
#       - name: Run
#         run: |
#           echo $BUILD_TYPE
#           echo $CXX11_ENABLED
#           echo $COMPILER
#           echo $DYNAWO_LIBRARY_TYPE
#         env:
#           BUILD_TYPE: ${{ matrix.build_type }}
#           CXX11_ENABLED: ${{ matrix.cxx11 }}
#           COMPILER: ${{ matrix.library_type }}
#           DYNAWO_LIBRARY_TYPE: ${{ matrix.compiler }}

# https://crontab.guru/once-a-day
# https://crontab.guru/examples.html
# https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md
